### ISSUE TITLE
Initialize clang-format

### ISSUE THREAD

**Issue by drodil** [plibither8/2048.cpp#29]
Project could use clang-format for formatting the source code so that it would be more generic across different contributors. More information here: https://clang.llvm.org/docs/ClangFormat.html

**Comment by plibither8** [comment]
Thanks for the suggestion, it is definitely required. I've been looking over the documentation, but I haven't found a proper way to install clang-format and make it so that the CI tests check whether it has been formatted correctly or not. Currently, I used `npm i -g clang-format` to install and run it and runs OK. But should all contributors install it this way to format the code? Thanks.

**Comment by drodil** [comment]
At least Ubuntu has the clang-format in APT repository. With 'apt-get install clang-format' you can install it. Main thing here would be to get the configuration file set up and then format all existing source code according to that. I have a snippet that could be used for the later part: https://gist.github.com/drodil/4541fb010c285beedcfd59792e8e20aa

There is this kind of sanitizer available https://github.com/cloderic/clang_format_check but not sure if it, or something else should be used. Also might be good idea to try out clang-tidy for sanitizing the code :+1:

**Comment by plibither8** [comment]
#42 closes this.
